#
# @file makefile
# @Brief the makefile of usart exmaple
# @author Yangliu, 869705086@qq.com
# @version V1.1
# @date 2017-01-27
#

OBJS +=
BINARY = cdcacm

OPT		:= -Os
CSTD	:= -std=c99
CXXSTD  := -std=c++98

include ../makefile
